language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  global:
    - MOODLE_BRANCH=MOODLE_39_STABLE
    - PLUGINS_BRANCH=MOODLE_39_WORKING
  matrix:
    - DB=mariadb
    - DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.0
  - nvm use 14.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
#  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
#  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
#  - moodle-plugin-ci phpdoc
#  - moodle-plugin-ci phpunit
#  - moodle-plugin-ci behat
