version: '3.8'
services:
  moodle:
    build: .
    container_name: moodle_app
    volumes:
      - .:/var/www/html
      - moodledata:/var/www/moodledata
      # MOUNT THE PHP CONFIG HERE:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php-fpm-override.conf:/usr/local/etc/php-fpm.d/zzz-override.conf
    restart: always
    env_file: .env

  web:
    image: nginx:alpine
    container_name: moodle_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/letsencrypt/live/${NGINX_HOST:-localhost}
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
    depends_on:
      - moodle
    restart: always

volumes:
  moodledata:
