version: '3.8'
services:
  moodle:
    build: .
    container_name: moodle_app
    volumes:
      - .:/var/www/html
      - moodledata:/var/www/moodledata
      # MOUNT THE PHP CONFIG HERE:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always

  web:
    image: nginx:alpine
    container_name: moodle_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - moodle
    restart: always

volumes:
  moodledata:
