name: Moodle Plugin CI

on: [pull_request]

jobs:
  test:
    runs-on: 'ubuntu-20.04'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      mariadb:
        image: mariadb:10.7.5
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.3'
            moodle-branch: 'MOODLE_311_STABLE'
            database: pgsql
            node-version: 'lts/gallium'
          - php: '8.0'
            moodle-branch: 'MOODLE_400_STABLE'
            database: pgsql
            node-version: 'lts/gallium'
          - php: '8.0'
            moodle-branch: 'MOODLE_400_STABLE'
            database: mariadb
            extensions: xmlrpc-beta
            node-version: 'lts/gallium'
          - php: '8.1'
            moodle-branch: 'MOODLE_403_STABLE'
            database: mariadb
            extensions: xmlrpc-beta
            node-version: '--lts'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: none

      - name: Initialise moodle-plugin-ci
        shell: bash -l {0}
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
          
          nvm install ${{ matrix.node-version }}
          nvm use ${{ matrix.node-version }}

      - name: Install moodle-plugin-ci
        shell: bash -l {0}
        run: |
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1 -vvv
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

#      - name: PHP Copy/Paste Detector
#        continue-on-error: true # This step will show errors but will not fail
#        if: ${{ always() }}
#        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker #--max-warnings 0

#      - name: Moodle PHPDoc Checker
#        if: ${{ always() }}
#        run: moodle-plugin-ci phpdoc

      - name: Validating
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

#      - name: Mustache Lint
#        if: ${{ always() }}
#        run: moodle-plugin-ci mustache

#      - name: Grunt
#        if: ${{ always() }}
#        run: moodle-plugin-ci grunt --max-lint-warnings 0

      - name: PHPUnit tests
        if: ${{ always() }}
        run: |
          moodle-plugin-ci phpunit
          cd moodle
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite tool_dataprivacy_testsuite --filter metadata_registry_test
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_testsuite --filter test_all_external_info
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_test

      - name: Behat features
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome
