language: php

addons:
  postgresql: '9.6'

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - PHPDOC_IGNORE_PATHS=jwt
    - MUSTACHE_IGNORE_PATHS=templates/mobile_view_page.mustache

jobs:
  include:
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=MOODLE_310_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || [ \
        "$MOODLE_BRANCH" != 'master' -a \
        "$MOODLE_BRANCH" != 'MOODLE_310_STABLE' -a \
        "$MOODLE_BRANCH" != 'MOODLE_39_STABLE' ]
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat