name: Push-to-ECS-Prod

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to ECS on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Master Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ECS_DEV_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.ECS_PROD_HOST_DNS }}
          REMOTE_USER: ${{ secrets.ECS_DEV_USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
